### ISSUE TITLE
Converting an HGT to OSM

### ISSUE THREAD

**Issue by ravenfeld** [roelderickx/contour-osm#1]
Hello I'm sorry to bother you but your project seems to be the most up to date and working on Mac OS X.
I would like to know how to convert HGT files to OSM with your script, I did not understand the command.
What I'm looking for is to have nice curves on my garmin watch, currently I'm using modified Phyghtmap but it's quite simplified I think.
What I'm looking for is curves like on the following map. https://topopirineos.blogspot.com/2020/06/descargas.html?sc=1654061891085#c7825600150912588561

Maybe it's the configuration, with Phyghtmap but I didn't find anything good, so I wanted to test with your script in case the result was cool.

You can test my map here: https://ravenfeld.gitlab.io/open-garmin-map/
And my code is here: https://gitlab.com/ravenfeld/garmincustommap
If you need to understand.

Thanks in advance for your help.

**Comment by roelderickx** [comment]
Hello,

I should have a detailed look when I have more time during the weekend.

As a quick start, a HGT file contains raster data (a height for each point on a surface) which you need to convert into vector data (contour lines) first. To do this use the GDAL commands:
```
gdal_contour -i 10 -snodata 32767 -a height inputfile.hgt contours.shp
shapeindex contours.shp
```

Next, you can either use ogr2osm or contour-osm to convert it into an osm file. Ogr2osm is somewhat more difficult to use since the tool has a different purpose, that's why I created contour-osm as a wrapper:
```
contour-osm.py --datasource contours.shp outputfile.osm
```
You can eventually pass `--osm` to generate an osm file in stead of a pbf file but the [mkgmap](http://www.mkgmap.org.uk/download/mkgmap.html) tool to create garmin maps support pbf input.

**Comment by ravenfeld** [comment]
Thanks a lot, I made it but it's still not as pretty as I would like. It looks like there is a lot of simplification of the stitches but maybe it's my HGT that are bad.

**Comment by roelderickx** [comment]
It may be the HGT file (try to download at least the 1 arc-second version), but the GDAL tool just generates contour lines which means the result will contain straight lines between calculated points. This looks rather unattractive, I admit.
@nobohan wrote a really nice article on how to improve this: https://www.champs-libres.coop/blog/post/2019-11-21-beautiful-contour-belgium/. Especially the paragraphs _Enlever les petits morceaux de courbes_ and _Avant de servir, lisser les courbes_ are important to you. I never had the time to try it for myself though.

**Comment by ravenfeld** [comment]
Thank you very much, I will read this, do you speak French?

**Comment by roelderickx** [comment]
Oui bien sûr, c'est une belle langue et j'ai beaucoup travaillé avec des belges francophones et des français. Par contre ma première langue est le néerlandais. 😉

**Comment by nobohan** [comment]
Hello. This can be hard to translate since this blog post was written to mimic a cooking recipe ;-)

Basically, what you can do is: 

1) remove very small lines: compute the length of the lines and discard the ones below a given threshold (to be determined by looking at the data, trial, ...)

2) most importantly, use a smoothing algo, such as `v.generalize` with the "snakes" algo. This step can be very CPU/time-consuming., so I suggest you'll try it on a small subset of your data. A good way to increase the speed is to cut the long lines, using eg the QGIS tool  "Split lines by maximum length"

**Comment by ravenfeld** [comment]
The HGT of 1° gives a good result but the osm files are huge
Thanks @nobohan  I'll check if it's applicable for Garmin watches.

**Comment by ravenfeld** [comment]
<img width="960" alt="Capture d’écran 2022-06-02 à 09 45 56" src="https://user-images.githubusercontent.com/3765114/171583485-f80c2a67-8e6a-4679-85cd-d304c749d885.png">
Thank you for your help I managed to get this, it was the configuration of parameters and the use of data in 1° of Lidar.

**Comment by roelderickx** [comment]
Good to read that - looks good to me too.
